### ISSUE TITLE
Deploying node app on Heroku. Errors abound.

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/independent-work#44]
So, my application is ready to be hosted and all the files have been pushed to Heroku, I've set up my session secret key with Heroku, and I've run `npm install` before I pushed the files with `git push heroku master`. The application still won't start though and keeps crashing whenever I try to reboot the server. 
The logs are as follows:

```
2015-12-11T16:37:40.010722+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-11T16:37:41.630816+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-11T16:37:44.835605+00:00 app[web.1]: 
2015-12-11T16:37:44.835609+00:00 app[web.1]: > blag-backend@0.0.0 start /app
2015-12-11T16:37:44.835610+00:00 app[web.1]: > node ./bin/www
2015-12-11T16:37:44.835611+00:00 app[web.1]: 
2015-12-11T16:37:46.296182+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2015-12-11T16:37:46.296639+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-11T16:37:46.296900+00:00 app[web.1]: npm ERR! node v5.1.1
2015-12-11T16:37:46.297473+00:00 app[web.1]: npm ERR! npm  v3.3.12
2015-12-11T16:37:46.297704+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-11T16:37:46.297911+00:00 app[web.1]: npm ERR! blag-backend@0.0.0 start
2015-12-11T16:37:46.298093+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-11T16:37:46.259319+00:00 app[web.1]: 
2015-12-11T16:37:46.298308+00:00 app[web.1]: npm ERR!
2015-12-11T16:37:46.299362+00:00 app[web.1]: npm ERR! Failed at the blag-backend@0.0.0 start script 'node ./bin/www'.
2015-12-11T16:37:46.299590+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2015-12-11T16:37:46.259326+00:00 app[web.1]: ^
2015-12-11T16:37:46.259330+00:00 app[web.1]: Error
2015-12-11T16:37:46.259331+00:00 app[web.1]: at Object.exports._errnoException (util.js:856:11)
2015-12-11T16:37:46.259332+00:00 app[web.1]: at exports._exceptionWithHostPort (util.js:879:20)
2015-12-11T16:37:46.299811+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the blag-backend package,
2015-12-11T16:37:46.300467+00:00 app[web.1]: npm ERR!     node ./bin/www
2015-12-11T16:37:46.309311+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-11T16:37:47.200984+00:00 heroku[web.1]: Process exited with status 1
2015-12-11T16:37:47.216556+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by gaand** [comment]
Are you specifying a PORT somewhere?  The error that jumped out at me was exports._exceptionWithHostPort.

**Comment by TeoPaolucci** [comment]
Where do I specify a port?   ._.

**Comment by gaand** [comment]
You don't.  I'm wondering if you did.  That error usually means you're trying to use a port that's in use.

**Comment by TeoPaolucci** [comment]
I don't think I did, and I don't have the app running locally anywhere.
Where might I look to see if this is the case though?

**Comment by TeoPaolucci** [comment]
Would this have something to do with mongoose? I couldn't find anything in forum about mongoose and Heroku and haven't done anything involving that yet. Right now my mongoose databases look like this: `mongoose.connect("mongodb://localhost/blag-db");`.
